simulacion:
  resolucion: [1900,1050]
  cantidad.P: 50
  cantidad.L: 50
  dt: 0.5

objetos:
  masa.P:
    mu: 300000
    sigma: 10000
  masa.L:
    mu: 300
    sigma: 50
  posicion_x:
    min: 100
    max: 1800
  posicion_y:
    min: 100
    max: 1000
  velocidad:
    min: -0.5
    max: 0.5
  