simulacion:
  resolucion: [1900,1000]
  cantidad.P: 300
  cantidad.L: 0
  dt: 0.01

objetos:
  masa.P:
    mu: 1000000000000
    sigma: 10000000000
  masa.L:
    mu: 1000000
    sigma: 1000
  posicion_x:
    min: 50
    max: 1850
  posicion_y:
    min: 50
    max: 950
  velocidad:
    min: -0.2
    max: 0.2
  escalado: 0.7
  