simulacion:
  resolucion: [1900,1000]
  cantidad.P: 50
  cantidad.L: 5
  dt: 0.5

objetos:
  masa.P:
    mu: 1000000000000
    sigma: 10000000000
  masa.L:
    mu: 1000000
    sigma: 1000
  posicion_x:
    min: 50
    max: 1850
  posicion_y:
    min: 50
    max: 950
  velocidad:
    min: -3
    max: 3
  escalado_a: 0.4
  escalado_b: 0.00003
  escalado_c: 4