simulacion:
  resolucion: [1920,1080]
  cantidad: 50
  dt: 0.5

objetos:
  masa:
    mu: 100000
    sigma: 50000
  posicion_x:
    min: 0
    max: 1920
  posicion_y:
    min: 0
    max: 1080
  velocidad:
    min: -5
    max: 5
  