simulacion:
  resolucion: [1900,1020]
  cantidad.P: 1
  cantidad.L: 1
  dt: 0.1

objetos:
  masa.P:
    mu: 1000000000000
    sigma: 1000000000
  masa.L:
    mu: 1000000
    sigma: 1000
  posicion_x:
    min: 200
    max: 1700
  posicion_y:
    min: 200
    max: 800
  velocidad:
    min: 0
    max: 0
  escalado: 0.3
  