simulacion:
  resolucion: [1900,1020]
  cantidad.P: 2
  cantidad.L: 6
  dt: 0.3

objetos:
  masa.P:
    mu: 3000000000
    sigma: 100000
  masa.L:
    mu: 30000
    sigma: 500
  posicion_x:
    min: 100
    max: 1800
  posicion_y:
    min: 100
    max: 1000
  velocidad:
    min: -0.5
    max: 0.5
  escalado: 0.3
  